manager:
  plan_outputs:
    html:
      class: octodns.provider.plan.PlanHtml

providers:
  config:
    class: octodns.provider.yaml.YamlProvider
    directory: ./
    enforce_order: False
    default_ttl: 300
  cloudflare:
    class: octodns_cloudflare.CloudflareProvider
    token: env/CLOUDFLARE_TOKEN
    strict_supports: true

zones:
  fxoi.io.:
    sources:
      - config
    targets:
      - cloudflare
