name: deploy

on:
  push:
    branches:
      - main

jobs:
  octodns-sync:
    name: Run `octodns-sync` with production.yaml
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3'
      - name: Install requirements
        run: pip install -r requirements.txt
      - uses: solvaholic/octodns-sync@main
        with:
          config_path: octodns.yaml
          doit: '--doit'
        env:
          CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
