name: test

on:
  push:
    branches:
      - '*'
      - '!main'
  pull_request:

jobs:
  octodns-sync:
    name: Run `octodns-sync` as dry-run
    runs-on: ubuntu-latest
    outputs:
      plan: ${{ steps.generate-plan.outputs.plan }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3'
      - name: Install requirements
        run: pip install -r requirements.txt
      - uses: felixoi/octodns-sync@9833aa80b95958cdaca9f9726b073b7f35fc00ca
        id: generate-plan
        with:
          config_path: octodns.yaml
          force: 'Yes'
        env:
          CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
  add-pr-comment:
    name: Add `octodns-sync` plan to comment
    if: github.event_name == 'pull_request'
    needs: [octodns-sync]
    runs-on: ubuntu-latest
    steps:
      - name: Find previous comment, if present
        uses: peter-evans/find-comment@v2
        id: fc
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: github-actions[bot]
          body-includes: Automatically generated by octodns-sync
      - name: Create or update comment
        id: prcomment
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-id: ${{ steps.fc.outputs.comment-id }}
          body: |
            ## OctoDNS Plan for `${{ github.ref }}`
            
            ${{ needs.octodns-sync.outputs.plan }}
            
            Automatically generated by octodns-sync
          edit-mode: replace
